name: Build Display Firmware
on: [push]
jobs:
  build-firmware:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install build tools
        run: sudo apt-get install -y gcc-arm-none-eabi binutils-arm-none-eabi
      - name: Build
        run: cd solum_BW_4.2_fw && make
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: |
            solum_BW_4.2_fw/QSPI.BWR.bin
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: solum_BW_4.2_fw/QSPI.BWR.bin

